# Generated by Django 5.2.6 on 2025-09-10 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('First_app', '0002_category_alter_book_options_book_isbn_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_completed',
            field=models.BooleanField(default=False, verbose_name='تکمیل شده'),
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('min_stock_level', models.PositiveIntegerField(default=5, verbose_name='حداقل موجودی')),
                ('max_stock_level', models.PositiveIntegerField(default=50, verbose_name='حداکثر موجودی')),
                ('auto_replenish', models.BooleanField(default=True, verbose_name='پر کردن خودکار موجودی')),
                ('last_replenished', models.DateTimeField(auto_now=True, verbose_name='آخرین پر کردن موجودی')),
                ('book', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='inventory', to='First_app.book')),
            ],
            options={
                'verbose_name': 'مدیریت انبار',
                'verbose_name_plural': 'مدیریت انبار',
            },
        ),
    ]
